options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - https://github.com/karlnicholas/bff.git
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --network
      - cloudbuild
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bff'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bff:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/bff:$COMMIT_SHA'